---
# Source: redis/templates/extra-list.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: access-secrets
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - update
  - create
---
# Source: redis/templates/extra-list.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: 'redis-to-secrets'
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: access-secrets
subjects:
- kind: ServiceAccount
  name: 'redis'
