---
# Source: redis/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: true
metadata:
  name: redis
  namespace: "podkova"
  labels:
    app.kubernetes.io/name: redis
    helm.sh/chart: redis-16.8.5
    app.kubernetes.io/instance: app
    app.kubernetes.io/managed-by: Helm
