---
# Source: redis/templates/custom/rolebinding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-to-secrets
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: access-secrets
subjects:
- kind: ServiceAccount
  name: redis
